#!/usr/bin/python
# vim: set fileencoding=utf-8

import time
import datetime
import json
import codecs
import requests
import markdown
import smtplib
from email.mime.text import MIMEText

now = datetime.datetime.now()
today = now.strftime("%Y-%m-%d")
weekago = (now - datetime.timedelta(days=6)).strftime("%Y-%m-%d")

url = 'http://redmine.org/issues.json'
params = {'assigned_to_id': 'me', 'status_id': '*', 'updated_on': '>=%s' % weekago}
headers = {'X-Redmine-API-Key': 'Your Redmine API Key', 'Content-Type': 'application/json; charset=utf-8'}
rest_resp = requests.get(url, params=params, headers=headers)
if rest_resp.status_code != 200:
    print "http error"
    exit(1)

ids = []
rest_json = json.loads(rest_resp.content)
for issue in rest_json['issues']:
    ids.append(issue['id'])

idx = 1
process = u""
issues = u""
for issue_id in ids:
    issue_url = 'http://redmine.org/issues/%d.json' % issue_id
    params = {'include': 'journals'}
    headers = {'X-Redmine-API-Key': 'Your Redmine API Key', 'Content-Type': 'application/json; charset=utf-8'}
    issue_resp = requests.get(issue_url, params=params, headers=headers)
    if issue_resp.status_code != 200:
        continue
    issue_json = json.loads(issue_resp.content)['issue']
    description = None
    for journal in reversed(issue_json['journals']):
        if journal['notes'] != "":
            description = journal['notes'].strip(' \t\n')
            break
    if description is None:
        description = issue_json['description'].strip(' \t\n')
    status = ['', '0%', '10%', '20%', '80%', '100%'][issue_json['status']['id']]
    process += u"%d. [Issue #%d %s] [issue-%d] [%s]\n\n" % (idx, issue_json['id'], issue_json['subject'], issue_json['id'], status)
    process += u"    %s\n\n" % description
    issues += u"[issue-%d]: http://redmine.org/issues/%d\n" % (issue_json['id'], issue_json['id'])
    idx += 1

md_text = u"# 周报 %s\n\n" % today
md_text += u"## 工作进展\n\n%s\n" % process
md_text += u"%s\n" % issues
md_text += u"*Auto-generated by wsrgen, written by Chen Gui <gui.g.chen@gmail.com>*"

md_file = codecs.open("wsr-%s.md" % now.strftime("%Y%m%d"), "w", encoding="utf-8", errors="xmlcharrefreplace")
md_file.write(md_text);


html = markdown.markdown(md_text)
#html_file = codecs.open("wsr.html", "w", encoding="utf-8", errors="xmlcharrefreplace")
#html_file.write(html);

me_email = "chengui@example.com"
to_list = ["chengui@example.com", ]
message = MIMEText(html, 'html', 'utf-8')
message['Subject'] = u"陈归的周报"
message['From'] = me_email
message['To'] = ';'.join(to_list)
server = smtplib.SMTP('smtp.gmail.com', 930)
server.login('chengui', 'password')
server.sendmail(me_email, to_list, message.as_string())
server.quit()
